name: Test Code Quality Action

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-code-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Code Quality Check
        uses: jtouley/github-code-quality@main